name = input("Enter your name:")
Address = input("Enter your address:")
Age = input("Enter your age:")
contact = input("Enter your number:")
print(f"Hello {name},your address is {Address},your age is {Age} and we may contact you on {contact}.")
